[web]
    addr="0.0.0.0:9807"
    version="0.1.0"
    runmode="dev"  # dev or prod
[db]
    pg="postgres://sa:cloud1688@localhost/lychee"
    connections=10
[redis]
    host="127.0.0.1"
    port="6379"
    username=""
    password=""
    with_secure=false
[langconf]
#此处有一个绝绝子的错误，执行shell： env | grep LANGUAGE
#env | grep LANG 获取语言环境变量 所以配置名字不能是lang或者language
    default="en-US"
    supported=["zh-CN","en-US"]